name: Push Health Check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: action/setup-python@v4
      with:
        python-version: 3.8

    - name: Run health.py
      run: |
        python health.py