name: New Book Notifier

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: action/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install Package
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run main.py
      run: |
        python health.py
        python main.py
      env:
        TOKEN: ${{ secrets.TOKEN }}